# Site
baseURL: "https://YOUR_PROJECT_DOMAIN"
languageCode: "pt-BR"
title: "YOUR_PROJECT_NAME"
googleAnalytics: "G-XXXXXXXXXX"

# Custom variables
params:
  title: "YOUR_PROJECT_NAME"
  description: "YOUR_PROJECT_DESCRIPTION"
  themeColor: "YOUR_PROJECT_THEME_COLOR"
  images: [site-feature-image.png]

# Build Configuration
cleanDestinationDir: true
disableHugoGeneratorInject: true
enableRobotsTXT: true
publishdir: "dist"
minify: true
disableKinds: [taxonomy, term, RSS]
build:
  noJSConfigInAssets: true
